workflows:
  my-workflow:
    instance_type: mac_pro
    environment:
      flutter: beta
      xcode: 12.5
    scripts:
      - name: Add provisioning profiles
        script: |
          set -e # exit on first failed command

          PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILES_HOME"
          echo ${PROVISIONING_PROFILE?} | base64 --decode > "$PROFILES_HOME/$(uuidgen).mobileprovision"
      - name: Build ipa for distribution
        script: xcode-project build-ipa \
                    --workspace "${XCODE_WORKSPACE?}"
    artifacts:
      - build/ios/ipa/*.ipa
