name: joke_calendar
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.7
  image_picker: ^0.8.5+3
  sqflite: ^2.0.3+1
  path: ^1.8.1
  flutter_local_notifications: ^9.3.1
  timezone: ^0.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 33 # android min sdk min:16, default 21
  
flutter:
  uses-material-design: true



