version: 2.1

jobs:
  "ios":
    macos: 
      xcode: "10.3.0"
    steps:
      - checkout
      - run:
          name: Install Flutter SDK Manager
          command: npm install -g fvm
      - run:
          name: Install Flutter SDK
          command: fvm stable && fvm 1.22.5
      - run:
          name: Compile iOS App
          command: flutter build ios --release --no-codesign 
      - store_artifacts:
          path: /build/
          destination: app.ipa
      

workflows:
  version: 2
  build:
    jobs:
      - "ios"
